import crypto from "node:crypto";
import type { IncomingMessage } from "node:http";
import { WebSocketServer, type WebSocket } from "ws";
import {
  BRIDGE_PROTOCOL_VERSION,
  CompanionAuthProofMessageSchema,
  CompanionRequestProgressMessageSchema,
  CompanionResponseMessageSchema,
  CompanionWireMessageSchema,
  MAX_IMAGE_BASE64_CHARACTERS,
  MAX_OPERATION_DURATION_MS,
  ErrorEnvelope,
  makeError,
  companionAuthPayload,
  companionAuthReadyPayload,
  type CompanionHelloMessage,
  type CompanionRequestMessage,
  type JsonValue,
  type OperationProgress,
} from "@foundry-mcp/protocol";

import type Database from "better-sqlite3";
import { HostEventStream } from "../intelligence/event-stream.js";
import type { EventCaptureOptions } from "../intelligence/event-ledger.js";
import { assertAllowedWebSocketHost, assertAllowedWebSocketOrigin } from "./websocket-origin.js";

const DEFAULT_MAX_PAYLOAD_BYTES = MAX_IMAGE_BASE64_CHARACTERS + 1024 * 1024;
const DEFAULT_AUTHENTICATION_TIMEOUT_MS = 10_000;
const DEFAULT_RATE_LIMIT_WINDOW_MS = 10_000;
const DEFAULT_MAX_MESSAGES_PER_CONNECTION = 1_000;
const DEFAULT_MAX_MESSAGES_GLOBAL = 10_000;
const CANCELLATION_ACK_TIMEOUT_MS = 1_000;
const MUTATION_METHODS = new Set([
  "documents.create",
  "documents.update",
  "assets.images.upload",
  "assets.images.generate",
  "assets.images.attach",
  "sessions.start",
  "sessions.append",
  "sessions.end",
  "sessions.reopen",
]);

export interface CompanionConnectionInfo extends CompanionHelloMessage {
  status: "connected";
  lastSeenAt: string;
}
export interface HostCompanionServerOptions {
  port?: number;
  host?: string;
  allowedOrigins: readonly string[];
  db: Database.Database;
  capture?: EventCaptureOptions;
  requestTimeoutMs?: number;
  /** Exact HTTP Host authorities accepted during WebSocket upgrade. Defaults to the listener. */
  allowedHosts?: readonly string[];
  maxPayloadBytes?: number;
  authenticationTimeoutMs?: number;
  rateLimitWindowMs?: number;
  maxMessagesPerConnection?: number;
  maxMessagesGlobal?: number;
  /** Raw 32-byte secret generated by the pairing workflow. */
  pairingSecret?: Buffer;
  onConnectionsChanged?: (connections: readonly CompanionConnectionInfo[]) => void;
}

export interface HostCompanionServer {
  address(): { host: string; port: number; endpoint: string };
  listConnections(): CompanionConnectionInfo[];
  request(
    connectionId: string,
    method: string,
    params?: Record<string, JsonValue>,
    requestId?: string,
    options?: CompanionRequestOptions,
  ): Promise<JsonValue>;
  close(): Promise<void>;
}

export interface CompanionRequestOptions {
  signal?: AbortSignal;
  deadline?: number;
  correlationId?: string;
  onProgress?: (progress: OperationProgress) => void | Promise<void>;
}

export class CompanionRequestError extends Error {
  constructor(readonly envelope: ErrorEnvelope) {
    super(envelope.message);
    this.name = "CompanionRequestError";
  }
}

interface PendingRequest {
  connectionId: string;
  message: CompanionRequestMessage;
  promise: Promise<JsonValue>;
  resolve(value: JsonValue): void;
  reject(error: Error): void;
  timer: ReturnType<typeof setTimeout>;
  correlationId: string;
  progressUpdates: number;
  onProgress?: ((progress: OperationProgress) => void | Promise<void>) | undefined;
  removeAbortListener?: (() => void) | undefined;
  cancelled: boolean;
  cancellationReason?: "cancelled" | "timeout" | undefined;
  dispatched: boolean;
  identity: string;
}

interface CompletedRequest {
  value: JsonValue;
  identity: string;
}

interface LiveConnection {
  socket: WebSocket;
  info: CompanionConnectionInfo;
}

interface RateWindow {
  startedAt: number;
  count: number;
}

function positiveInteger(value: number, name: string): number {
  if (!Number.isSafeInteger(value) || value <= 0) {
    throw new Error(`${name} must be a positive safe integer`);
  }
  return value;
}

function canonicalJson(value: unknown): string {
  if (value === null || typeof value !== "object") return JSON.stringify(value) ?? "null";
  if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`;
  return `{${Object.entries(value as Record<string, unknown>)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([key, child]) => `${JSON.stringify(key)}:${canonicalJson(child)}`)
    .join(",")}}`;
}

/** Fixed-size replay identity; request bodies are never retained by the completed-request cache. */
export function companionRequestIdentityDigest(
  method: string,
  params: Record<string, JsonValue>,
  correlationId: string,
): string {
  return crypto
    .createHash("sha256")
    .update(canonicalJson({ method, params, correlationId }), "utf8")
    .digest("base64url");
}

function listenerAuthority(host: string, port: number): string {
  const authorityHost = host.includes(":") && !host.startsWith("[") ? `[${host}]` : host;
  return `${authorityHost.toLowerCase()}:${port.toString()}`;
}

function consumeRate(window: RateWindow, now: number, windowMs: number, maximum: number): boolean {
  if (now - window.startedAt >= windowMs) {
    window.startedAt = now;
    window.count = 0;
  }
  window.count += 1;
  return window.count <= maximum;
}

let requestCounter = 0;

/** Real loopback WebSocket endpoint for the browser companion. */
export async function startHostCompanionServer(
  options: HostCompanionServerOptions,
): Promise<HostCompanionServer> {
  if (!options.pairingSecret || options.pairingSecret.length !== 32) {
    throw new Error("a valid 32-byte companion pairing secret is required");
  }
  const pairingSecret = Buffer.from(options.pairingSecret);
  const host = options.host ?? "127.0.0.1";
  const maxPayloadBytes = positiveInteger(
    options.maxPayloadBytes ?? DEFAULT_MAX_PAYLOAD_BYTES,
    "maxPayloadBytes",
  );
  const authenticationTimeoutMs = positiveInteger(
    options.authenticationTimeoutMs ?? DEFAULT_AUTHENTICATION_TIMEOUT_MS,
    "authenticationTimeoutMs",
  );
  const rateLimitWindowMs = positiveInteger(
    options.rateLimitWindowMs ?? DEFAULT_RATE_LIMIT_WINDOW_MS,
    "rateLimitWindowMs",
  );
  const maxMessagesPerConnection = positiveInteger(
    options.maxMessagesPerConnection ?? DEFAULT_MAX_MESSAGES_PER_CONNECTION,
    "maxMessagesPerConnection",
  );
  const maxMessagesGlobal = positiveInteger(
    options.maxMessagesGlobal ?? DEFAULT_MAX_MESSAGES_GLOBAL,
    "maxMessagesGlobal",
  );
  let allowedHosts: readonly string[] = options.allowedHosts ? [...options.allowedHosts] : [];
  if (options.allowedHosts) {
    for (const allowedHost of options.allowedHosts) {
      assertAllowedWebSocketHost(allowedHost, options.allowedHosts);
    }
  }
  const eventStream = new HostEventStream(options.db, options.capture);
  const connections = new Map<string, LiveConnection>();
  const pending = new Map<string, PendingRequest>();
  const completed = new Map<string, CompletedRequest>();
  let closing = false;
  let closePromise: Promise<void> | undefined;
  const globalRate: RateWindow = { startedAt: Date.now(), count: 0 };
  const connectionSnapshot = (): CompanionConnectionInfo[] =>
    [...connections.values()]
      .map(({ info }) => ({ ...info }))
      .sort((left, right) => left.connectionId.localeCompare(right.connectionId));
  const notifyConnectionsChanged = (): void => {
    options.onConnectionsChanged?.(connectionSnapshot());
  };
  const wss = new WebSocketServer({
    port: options.port ?? 0,
    host,
    maxPayload: maxPayloadBytes,
    verifyClient: (info: { origin: string; secure: boolean; req: IncomingMessage }) => {
      try {
        assertAllowedWebSocketOrigin(info.origin, options.allowedOrigins);
        assertAllowedWebSocketHost(info.req.headers.host, allowedHosts);
        return true;
      } catch {
        return false;
      }
    },
  });

  const closeSocket = (socket: WebSocket, code: number, reason: string): void => {
    if (socket.readyState === socket.OPEN) socket.close(code, reason);
  };

  const send = (socket: WebSocket, value: unknown): void => {
    if (socket.readyState !== socket.OPEN) return;
    socket.send(JSON.stringify(value), () => undefined);
  };

  const requestKey = (connectionId: string, requestId: string): string =>
    JSON.stringify([connectionId, requestId]);

  const authProof = (payload: string): string =>
    crypto.createHmac("sha256", pairingSecret).update(payload, "utf8").digest("base64url");

  const validProof = (payload: string, supplied: string): boolean => {
    const expected = Buffer.from(authProof(payload), "base64url");
    const candidate = Buffer.from(supplied, "base64url");
    return candidate.length === expected.length && crypto.timingSafeEqual(expected, candidate);
  };

  const unacknowledgedCancellation = (
    request: PendingRequest,
    reason: "cancelled" | "timeout",
  ): CompanionRequestError => {
    const mutation = request.dispatched && MUTATION_METHODS.has(request.message.method);
    return new CompanionRequestError(
      makeError(
        mutation ? "INDETERMINATE_MUTATION" : reason === "timeout" ? "TIMEOUT" : "CANCELLED",
        mutation
          ? `Mutation ${request.message.method} did not acknowledge cancellation; reconcile state before retrying`
          : reason === "timeout"
            ? `Companion request deadline elapsed: ${request.message.method}`
            : `Companion request was cancelled: ${request.message.method}`,
        false,
        {
          correlationId: request.correlationId,
          ...(mutation ? { indeterminate: true, reconciliationRequired: true } : {}),
        },
      ),
    );
  };

  const cancelPending = (
    key: string,
    reason: "cancelled" | "timeout",
    notifyCompanion = true,
  ): void => {
    const request = pending.get(key);
    if (!request) return;
    if (request.cancelled) return;
    clearTimeout(request.timer);
    request.removeAbortListener?.();
    request.removeAbortListener = undefined;
    request.cancelled = true;
    request.cancellationReason = reason;
    const live = connections.get(request.connectionId);
    if (notifyCompanion && live) {
      send(live.socket, {
        type: "request.cancel",
        id: request.message.id,
        correlationId: request.correlationId,
        reason,
      });
    }
    request.timer = setTimeout(() => {
      if (pending.get(key) !== request) return;
      pending.delete(key);
      request.reject(unacknowledgedCancellation(request, reason));
    }, CANCELLATION_ACK_TIMEOUT_MS);
    request.timer.unref?.();
  };

  wss.on("connection", (socket, request) => {
    socket.on("error", () => undefined);
    let origin: string;
    try {
      origin = assertAllowedWebSocketOrigin(request.headers.origin, options.allowedOrigins);
      assertAllowedWebSocketHost(request.headers.host, allowedHosts);
    } catch {
      closeSocket(socket, 1008, "WebSocket Origin or Host is not allowed");
      return;
    }
    const challenge = crypto.randomBytes(32).toString("base64url");
    let connectionId: string | undefined;
    const connectionRate: RateWindow = { startedAt: Date.now(), count: 0 };
    const authenticationTimer = setTimeout(() => {
      closeSocket(socket, 1008, "companion authentication timed out");
    }, authenticationTimeoutMs);
    authenticationTimer.unref?.();
    send(socket, {
      type: "auth.challenge",
      protocolVersion: BRIDGE_PROTOCOL_VERSION,
      challenge,
      origin,
    });
    socket.on("message", (data) => {
      const now = Date.now();
      const withinConnectionLimit = consumeRate(
        connectionRate,
        now,
        rateLimitWindowMs,
        maxMessagesPerConnection,
      );
      const withinGlobalLimit = consumeRate(globalRate, now, rateLimitWindowMs, maxMessagesGlobal);
      if (!withinConnectionLimit || !withinGlobalLimit) {
        closeSocket(socket, 1008, "companion message rate limit exceeded");
        return;
      }
      let decoded: unknown;
      try {
        decoded = JSON.parse(data.toString()) as unknown;
      } catch {
        closeSocket(socket, 1003, "invalid JSON");
        return;
      }
      if (!connectionId) {
        const proof = CompanionAuthProofMessageSchema.safeParse(decoded);
        if (
          !proof.success ||
          !validProof(companionAuthPayload(challenge, origin, proof.data.hello), proof.data.proof)
        ) {
          closeSocket(socket, 1008, "valid companion pairing proof required");
          return;
        }
        clearTimeout(authenticationTimer);
        const hello = proof.data.hello;
        connectionId = hello.connectionId;
        const prior = connections.get(connectionId);
        if (prior && prior.socket !== socket) {
          closeSocket(prior.socket, 1012, "companion reconnected");
        }
        const info: CompanionConnectionInfo = {
          ...hello,
          status: "connected",
          lastSeenAt: new Date().toISOString(),
        };
        connections.set(connectionId, { socket, info });
        notifyConnectionsChanged();
        send(socket, {
          type: "auth.ready",
          connectionId,
          proof: authProof(companionAuthReadyPayload(challenge, origin, hello)),
        });
        send(socket, eventStream.resume(connectionId));
        for (const request of pending.values()) {
          if (request.connectionId === connectionId) {
            if (request.cancelled) continue;
            send(socket, request.message);
          }
        }
        return;
      }

      const message = CompanionWireMessageSchema.safeParse(decoded);
      if (!message.success) {
        closeSocket(socket, 1003, "invalid companion message");
        return;
      }
      if (connections.get(connectionId)?.socket !== socket) return;
      const live = connections.get(connectionId);
      if (live) live.info.lastSeenAt = new Date().toISOString();
      if (message.data.type === "event") {
        if (message.data.connectionId !== connectionId) {
          closeSocket(socket, 1008, "connectionId mismatch");
          return;
        }
        try {
          send(socket, eventStream.ingest(message.data));
        } catch {
          closeSocket(socket, 1011, "event reconciliation failed");
        }
        return;
      }
      if (message.data.type === "request.progress") {
        const progress = CompanionRequestProgressMessageSchema.parse(message.data);
        const key = requestKey(connectionId, progress.id);
        const request = pending.get(key);
        if (!request || !request.onProgress || request.progressUpdates >= 1_000) return;
        request.progressUpdates += 1;
        void Promise.resolve(request.onProgress(progress.progress)).catch(() => undefined);
        return;
      }
      if (message.data.type !== "response") return;
      const response = CompanionResponseMessageSchema.parse(message.data);
      const key = requestKey(connectionId, response.id);
      const request = pending.get(key);
      if (!request) return;
      clearTimeout(request.timer);
      request.removeAbortListener?.();
      pending.delete(key);
      const result: JsonValue = response.ok
        ? (response.value as JsonValue)
        : ({ ok: false, error: response.error as JsonValue } as JsonValue);
      completed.set(key, { value: result, identity: request.identity });
      while (completed.size > 500) completed.delete(completed.keys().next().value as string);
      request.resolve(result);
    });
    socket.on("close", () => {
      clearTimeout(authenticationTimer);
      if (connectionId && connections.get(connectionId)?.socket === socket) {
        connections.delete(connectionId);
        notifyConnectionsChanged();
      }
    });
  });

  await new Promise<void>((resolve, reject) => {
    wss.once("listening", () => {
      if (allowedHosts.length === 0) {
        const address = wss.address();
        if (typeof address === "string" || address === null) {
          reject(new Error("companion WebSocket server address is unavailable"));
          return;
        }
        allowedHosts = [listenerAuthority(host, address.port)];
      }
      resolve();
    });
    wss.once("error", reject);
  });

  return {
    address: () => {
      const address = wss.address();
      if (typeof address === "string" || address === null)
        throw new Error("companion WebSocket server address is unavailable");
      return { host, port: address.port, endpoint: `ws://${host}:${address.port.toString()}` };
    },
    listConnections: connectionSnapshot,
    request: (connectionId, method, params = {}, requestId, requestOptions = {}) => {
      const id = requestId ?? `host-${Date.now().toString(36)}-${(++requestCounter).toString(36)}`;
      const correlationId = (requestOptions.correlationId ?? id).slice(0, 128);
      if (closing) {
        return Promise.reject(
          new CompanionRequestError(
            makeError("OFFLINE_BRIDGE", "Companion server is closing", false, {
              correlationId,
            }),
          ),
        );
      }
      const key = requestKey(connectionId, id);
      const requestParams = { ...params, connectionId };
      const identity = companionRequestIdentityDigest(method, requestParams, correlationId);
      const priorResult = completed.get(key);
      if (priorResult !== undefined) {
        return priorResult.identity === identity
          ? Promise.resolve(priorResult.value)
          : Promise.reject(
              new CompanionRequestError(
                makeError("CONFLICT", "Completed companion request id was reused", false, {
                  correlationId,
                }),
              ),
            );
      }
      const priorPending = pending.get(key);
      if (priorPending) {
        return priorPending.identity === identity
          ? priorPending.promise
          : Promise.reject(
              new CompanionRequestError(
                makeError("CONFLICT", "In-flight companion request id was reused", false, {
                  correlationId,
                }),
              ),
            );
      }
      const now = Date.now();
      const configuredTimeout = options.requestTimeoutMs ?? 30_000;
      const maximumDeadline = now + Math.min(configuredTimeout, MAX_OPERATION_DURATION_MS);
      const deadline = Math.min(requestOptions.deadline ?? maximumDeadline, maximumDeadline);
      if (requestOptions.signal?.aborted || deadline <= now) {
        return Promise.reject(
          new CompanionRequestError(
            makeError(
              requestOptions.signal?.aborted ? "CANCELLED" : "TIMEOUT",
              requestOptions.signal?.aborted
                ? `Companion request was cancelled before dispatch: ${method}`
                : `Companion request deadline elapsed before dispatch: ${method}`,
              false,
              { correlationId },
            ),
          ),
        );
      }
      let resolveRequest: (value: JsonValue) => void = () => undefined;
      let rejectRequest: (error: Error) => void = () => undefined;
      const promise = new Promise<JsonValue>((resolve, reject) => {
        resolveRequest = resolve;
        rejectRequest = reject;
      });
      const message: CompanionRequestMessage = {
        type: "request",
        id,
        method,
        params: requestParams,
        control: {
          deadline,
          correlationId,
          progress: requestOptions.onProgress !== undefined,
        },
      };
      const timer = setTimeout(
        () => {
          cancelPending(key, "timeout");
        },
        Math.max(1, deadline - now),
      );
      timer.unref?.();
      let removeAbortListener: (() => void) | undefined;
      if (requestOptions.signal) {
        const onAbort = (): void => cancelPending(key, "cancelled");
        requestOptions.signal.addEventListener("abort", onAbort, { once: true });
        removeAbortListener = () => requestOptions.signal?.removeEventListener("abort", onAbort);
      }
      pending.set(key, {
        connectionId,
        message,
        promise,
        resolve: resolveRequest,
        reject: rejectRequest,
        timer,
        correlationId,
        progressUpdates: 0,
        onProgress: requestOptions.onProgress,
        removeAbortListener,
        cancelled: false,
        dispatched: connections.has(connectionId),
        identity,
      });
      const live = connections.get(connectionId);
      if (live) send(live.socket, message);
      return promise;
    },
    close: () => {
      if (closePromise) return closePromise;
      closing = true;
      closePromise = (async () => {
        for (const request of pending.values()) {
          clearTimeout(request.timer);
          request.removeAbortListener?.();
          request.reject(
            request.cancelled
              ? unacknowledgedCancellation(request, request.cancellationReason ?? "cancelled")
              : new CompanionRequestError(
                  makeError("OFFLINE_BRIDGE", "Companion server closed", false, {
                    correlationId: request.correlationId,
                  }),
                ),
          );
        }
        pending.clear();
        for (const socket of wss.clients) socket.terminate();
        connections.clear();
        notifyConnectionsChanged();
        try {
          await new Promise<void>((resolve, reject) => {
            wss.close((error) => (error ? reject(error) : resolve()));
          });
        } finally {
          pairingSecret.fill(0);
        }
      })();
      return closePromise;
    },
  };
}
