import crypto from "node:crypto";
import type { IncomingMessage } from "node:http";
import { WebSocketServer, type WebSocket } from "ws";
import {
  BRIDGE_PROTOCOL_VERSION,
  CompanionAuthProofMessageSchema,
  CompanionResponseMessageSchema,
  CompanionWireMessageSchema,
  MAX_IMAGE_BASE64_CHARACTERS,
  companionAuthPayload,
  companionAuthReadyPayload,
  type CompanionHelloMessage,
  type CompanionRequestMessage,
  type JsonValue,
} from "@foundry-mcp/protocol";

import type Database from "better-sqlite3";
import { HostEventStream } from "../intelligence/event-stream.js";
import type { EventCaptureOptions } from "../intelligence/event-ledger.js";
import { assertAllowedWebSocketHost, assertAllowedWebSocketOrigin } from "./websocket-origin.js";

const DEFAULT_MAX_PAYLOAD_BYTES = MAX_IMAGE_BASE64_CHARACTERS + 1024 * 1024;
const DEFAULT_AUTHENTICATION_TIMEOUT_MS = 10_000;
const DEFAULT_RATE_LIMIT_WINDOW_MS = 10_000;
const DEFAULT_MAX_MESSAGES_PER_CONNECTION = 1_000;
const DEFAULT_MAX_MESSAGES_GLOBAL = 10_000;

export interface CompanionConnectionInfo extends CompanionHelloMessage {
  status: "connected";
  lastSeenAt: string;
}
export interface HostCompanionServerOptions {
  port?: number;
  host?: string;
  allowedOrigins: readonly string[];
  db: Database.Database;
  capture?: EventCaptureOptions;
  requestTimeoutMs?: number;
  /** Exact HTTP Host authorities accepted during WebSocket upgrade. Defaults to the listener. */
  allowedHosts?: readonly string[];
  maxPayloadBytes?: number;
  authenticationTimeoutMs?: number;
  rateLimitWindowMs?: number;
  maxMessagesPerConnection?: number;
  maxMessagesGlobal?: number;
  /** Raw 32-byte secret generated by the pairing workflow. */
  pairingSecret?: Buffer;
  onConnectionsChanged?: (connections: readonly CompanionConnectionInfo[]) => void;
}

export interface HostCompanionServer {
  address(): { host: string; port: number; endpoint: string };
  listConnections(): CompanionConnectionInfo[];
  request(
    connectionId: string,
    method: string,
    params?: Record<string, JsonValue>,
    requestId?: string,
  ): Promise<JsonValue>;
  close(): Promise<void>;
}

interface PendingRequest {
  connectionId: string;
  message: CompanionRequestMessage;
  promise: Promise<JsonValue>;
  resolve(value: JsonValue): void;
  reject(error: Error): void;
  timer: ReturnType<typeof setTimeout>;
}

interface CompletedRequest {
  value: JsonValue;
}

interface LiveConnection {
  socket: WebSocket;
  info: CompanionConnectionInfo;
}

interface RateWindow {
  startedAt: number;
  count: number;
}

function positiveInteger(value: number, name: string): number {
  if (!Number.isSafeInteger(value) || value <= 0) {
    throw new Error(`${name} must be a positive safe integer`);
  }
  return value;
}

function listenerAuthority(host: string, port: number): string {
  const authorityHost = host.includes(":") && !host.startsWith("[") ? `[${host}]` : host;
  return `${authorityHost.toLowerCase()}:${port.toString()}`;
}

function consumeRate(window: RateWindow, now: number, windowMs: number, maximum: number): boolean {
  if (now - window.startedAt >= windowMs) {
    window.startedAt = now;
    window.count = 0;
  }
  window.count += 1;
  return window.count <= maximum;
}

let requestCounter = 0;

/** Real loopback WebSocket endpoint for the browser companion. */
export async function startHostCompanionServer(
  options: HostCompanionServerOptions,
): Promise<HostCompanionServer> {
  if (!options.pairingSecret || options.pairingSecret.length !== 32) {
    throw new Error("a valid 32-byte companion pairing secret is required");
  }
  const pairingSecret = Buffer.from(options.pairingSecret);
  const host = options.host ?? "127.0.0.1";
  const maxPayloadBytes = positiveInteger(
    options.maxPayloadBytes ?? DEFAULT_MAX_PAYLOAD_BYTES,
    "maxPayloadBytes",
  );
  const authenticationTimeoutMs = positiveInteger(
    options.authenticationTimeoutMs ?? DEFAULT_AUTHENTICATION_TIMEOUT_MS,
    "authenticationTimeoutMs",
  );
  const rateLimitWindowMs = positiveInteger(
    options.rateLimitWindowMs ?? DEFAULT_RATE_LIMIT_WINDOW_MS,
    "rateLimitWindowMs",
  );
  const maxMessagesPerConnection = positiveInteger(
    options.maxMessagesPerConnection ?? DEFAULT_MAX_MESSAGES_PER_CONNECTION,
    "maxMessagesPerConnection",
  );
  const maxMessagesGlobal = positiveInteger(
    options.maxMessagesGlobal ?? DEFAULT_MAX_MESSAGES_GLOBAL,
    "maxMessagesGlobal",
  );
  let allowedHosts: readonly string[] = options.allowedHosts ? [...options.allowedHosts] : [];
  if (options.allowedHosts) {
    for (const allowedHost of options.allowedHosts) {
      assertAllowedWebSocketHost(allowedHost, options.allowedHosts);
    }
  }
  const eventStream = new HostEventStream(options.db, options.capture);
  const connections = new Map<string, LiveConnection>();
  const pending = new Map<string, PendingRequest>();
  const completed = new Map<string, CompletedRequest>();
  const globalRate: RateWindow = { startedAt: Date.now(), count: 0 };
  const connectionSnapshot = (): CompanionConnectionInfo[] =>
    [...connections.values()]
      .map(({ info }) => ({ ...info }))
      .sort((left, right) => left.connectionId.localeCompare(right.connectionId));
  const notifyConnectionsChanged = (): void => {
    options.onConnectionsChanged?.(connectionSnapshot());
  };
  const wss = new WebSocketServer({
    port: options.port ?? 0,
    host,
    maxPayload: maxPayloadBytes,
    verifyClient: (info: { origin: string; secure: boolean; req: IncomingMessage }) => {
      try {
        assertAllowedWebSocketOrigin(info.origin, options.allowedOrigins);
        assertAllowedWebSocketHost(info.req.headers.host, allowedHosts);
        return true;
      } catch {
        return false;
      }
    },
  });

  const closeSocket = (socket: WebSocket, code: number, reason: string): void => {
    if (socket.readyState === socket.OPEN) socket.close(code, reason);
  };

  const send = (socket: WebSocket, value: unknown): void => {
    if (socket.readyState !== socket.OPEN) return;
    socket.send(JSON.stringify(value), () => undefined);
  };

  const requestKey = (connectionId: string, requestId: string): string =>
    JSON.stringify([connectionId, requestId]);

  const authProof = (payload: string): string =>
    crypto.createHmac("sha256", pairingSecret).update(payload, "utf8").digest("base64url");

  const validProof = (payload: string, supplied: string): boolean => {
    const expected = Buffer.from(authProof(payload), "base64url");
    const candidate = Buffer.from(supplied, "base64url");
    return candidate.length === expected.length && crypto.timingSafeEqual(expected, candidate);
  };

  wss.on("connection", (socket, request) => {
    socket.on("error", () => undefined);
    let origin: string;
    try {
      origin = assertAllowedWebSocketOrigin(request.headers.origin, options.allowedOrigins);
      assertAllowedWebSocketHost(request.headers.host, allowedHosts);
    } catch {
      closeSocket(socket, 1008, "WebSocket Origin or Host is not allowed");
      return;
    }
    const challenge = crypto.randomBytes(32).toString("base64url");
    let connectionId: string | undefined;
    const connectionRate: RateWindow = { startedAt: Date.now(), count: 0 };
    const authenticationTimer = setTimeout(() => {
      closeSocket(socket, 1008, "companion authentication timed out");
    }, authenticationTimeoutMs);
    authenticationTimer.unref?.();
    send(socket, {
      type: "auth.challenge",
      protocolVersion: BRIDGE_PROTOCOL_VERSION,
      challenge,
      origin,
    });
    socket.on("message", (data) => {
      const now = Date.now();
      const withinConnectionLimit = consumeRate(
        connectionRate,
        now,
        rateLimitWindowMs,
        maxMessagesPerConnection,
      );
      const withinGlobalLimit = consumeRate(globalRate, now, rateLimitWindowMs, maxMessagesGlobal);
      if (!withinConnectionLimit || !withinGlobalLimit) {
        closeSocket(socket, 1008, "companion message rate limit exceeded");
        return;
      }
      let decoded: unknown;
      try {
        decoded = JSON.parse(data.toString()) as unknown;
      } catch {
        closeSocket(socket, 1003, "invalid JSON");
        return;
      }
      if (!connectionId) {
        const proof = CompanionAuthProofMessageSchema.safeParse(decoded);
        if (
          !proof.success ||
          !validProof(companionAuthPayload(challenge, origin, proof.data.hello), proof.data.proof)
        ) {
          closeSocket(socket, 1008, "valid companion pairing proof required");
          return;
        }
        clearTimeout(authenticationTimer);
        const hello = proof.data.hello;
        connectionId = hello.connectionId;
        const prior = connections.get(connectionId);
        if (prior && prior.socket !== socket) {
          closeSocket(prior.socket, 1012, "companion reconnected");
        }
        const info: CompanionConnectionInfo = {
          ...hello,
          status: "connected",
          lastSeenAt: new Date().toISOString(),
        };
        connections.set(connectionId, { socket, info });
        notifyConnectionsChanged();
        send(socket, {
          type: "auth.ready",
          connectionId,
          proof: authProof(companionAuthReadyPayload(challenge, origin, hello)),
        });
        send(socket, eventStream.resume(connectionId));
        for (const request of pending.values()) {
          if (request.connectionId === connectionId) {
            send(socket, request.message);
          }
        }
        return;
      }

      const message = CompanionWireMessageSchema.safeParse(decoded);
      if (!message.success) {
        closeSocket(socket, 1003, "invalid companion message");
        return;
      }
      if (connections.get(connectionId)?.socket !== socket) return;
      const live = connections.get(connectionId);
      if (live) live.info.lastSeenAt = new Date().toISOString();
      if (message.data.type === "event") {
        if (message.data.connectionId !== connectionId) {
          closeSocket(socket, 1008, "connectionId mismatch");
          return;
        }
        try {
          send(socket, eventStream.ingest(message.data));
        } catch {
          closeSocket(socket, 1011, "event reconciliation failed");
        }
        return;
      }
      if (message.data.type !== "response") return;
      const response = CompanionResponseMessageSchema.parse(message.data);
      const key = requestKey(connectionId, response.id);
      const request = pending.get(key);
      if (!request) return;
      clearTimeout(request.timer);
      pending.delete(key);
      const result: JsonValue = response.ok
        ? (response.value as JsonValue)
        : ({ ok: false, error: response.error as JsonValue } as JsonValue);
      completed.set(key, { value: result });
      while (completed.size > 500) completed.delete(completed.keys().next().value as string);
      request.resolve(result);
    });
    socket.on("close", () => {
      clearTimeout(authenticationTimer);
      if (connectionId && connections.get(connectionId)?.socket === socket) {
        connections.delete(connectionId);
        notifyConnectionsChanged();
      }
    });
  });

  await new Promise<void>((resolve, reject) => {
    wss.once("listening", () => {
      if (allowedHosts.length === 0) {
        const address = wss.address();
        if (typeof address === "string" || address === null) {
          reject(new Error("companion WebSocket server address is unavailable"));
          return;
        }
        allowedHosts = [listenerAuthority(host, address.port)];
      }
      resolve();
    });
    wss.once("error", reject);
  });

  return {
    address: () => {
      const address = wss.address();
      if (typeof address === "string" || address === null)
        throw new Error("companion WebSocket server address is unavailable");
      return { host, port: address.port, endpoint: `ws://${host}:${address.port.toString()}` };
    },
    listConnections: connectionSnapshot,
    request: (connectionId, method, params = {}, requestId) => {
      const id = requestId ?? `host-${Date.now().toString(36)}-${(++requestCounter).toString(36)}`;
      const key = requestKey(connectionId, id);
      const priorResult = completed.get(key);
      if (priorResult !== undefined) return Promise.resolve(priorResult.value);
      const priorPending = pending.get(key);
      if (priorPending) return priorPending.promise;
      let resolveRequest: (value: JsonValue) => void = () => undefined;
      let rejectRequest: (error: Error) => void = () => undefined;
      const promise = new Promise<JsonValue>((resolve, reject) => {
        resolveRequest = resolve;
        rejectRequest = reject;
      });
      const message: CompanionRequestMessage = {
        type: "request",
        id,
        method,
        params: { ...params, connectionId },
      };
      const timer = setTimeout(() => {
        pending.delete(key);
        rejectRequest(new Error(`companion request timed out: ${method}`));
      }, options.requestTimeoutMs ?? 30_000);
      timer.unref?.();
      pending.set(key, {
        connectionId,
        message,
        promise,
        resolve: resolveRequest,
        reject: rejectRequest,
        timer,
      });
      const live = connections.get(connectionId);
      if (live) send(live.socket, message);
      return promise;
    },
    close: async () => {
      for (const request of pending.values()) {
        clearTimeout(request.timer);
        request.reject(new Error("companion server closed"));
      }
      pending.clear();
      for (const { socket } of connections.values()) socket.terminate();
      connections.clear();
      notifyConnectionsChanged();
      await new Promise<void>((resolve, reject) => {
        wss.close((error) => (error ? reject(error) : resolve()));
      });
      pairingSecret.fill(0);
    },
  };
}
